In [7]:
import torch
import torch.optim as optim
import numpy as np



In [36]:
a = torch.arange(10)
b = torch.tensor([1+1j, 2+2j, 1j])


In [37]:
torch.angle(b)

tensor([0.7854, 0.7854, 1.5708])

In [2]:
3//2


1

In [3]:
lst = [1, 2, 3, 4]

In [20]:
a = torch.arange(10)
b = torch.arange(5)
print(a)
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4])


In [19]:
a.unsqueeze(1) * b

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16],
        [ 0,  5, 10, 15, 20],
        [ 0,  6, 12, 18, 24],
        [ 0,  7, 14, 21, 28],
        [ 0,  8, 16, 24, 32],
        [ 0,  9, 18, 27, 36]])