In [6]:
import torch
import torch.optim as optim
import numpy as np



In [19]:
a = torch.arange(10)
b = torch.arange(3)


In [20]:
print(a)
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2])


In [25]:
b.unsqueeze(1).shape

torch.Size([3, 1])

In [26]:
a.shape

torch.Size([10])

In [27]:
a + b.unsqueeze(1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [29]:
b.unsqueeze(0).shape

torch.Size([1, 3])

In [30]:
a + b.unsqueeze(0)

RuntimeError: The size of tensor a (10) must match the size of tensor b (3) at non-singleton dimension 1